version: '3.0'
services:
  base:
    build: .
    volumes:
    - $DIR/.ssh/:/home/developer/.ssh/
    - $DIR/.aws/:/home/developer/.aws/
    - $DIR/development_backup:/home/developer/shared
      # entrypoint: zsh
    stdin_open: true
    tty: true
